In [1]:
import numpy as np

In [20]:
a=np.array([1,2,3])
b=np.array([(1,2,3),(4,5,6)])

In [21]:
a.shape

(3,)

In [22]:
b.shape

(2, 3)

In [23]:
len(a)

3

In [24]:
len(b)

2

In [25]:
b.ndim

2

In [26]:
a.ndim

1

In [27]:
b.size

6

In [28]:
a.size

3

In [29]:
c=b.astype(str)

In [30]:
c.dtype

dtype('<U11')

In [31]:
a.sum()

6

In [32]:
b=b.sum()
print(b)

21


a.min().show()

print(a.exp(2))

In [33]:
a.size

3

In [34]:
a+a

array([2, 4, 6])

In [35]:
a*2

array([2, 4, 6])

In [36]:
b*2

42

In [37]:
np.exp(b)

1318815734.4832146

In [38]:
b.mean()

21.0

In [40]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
b.corrcoef()

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'

In [39]:
a[2]

3

In [40]:
b[:1]

IndexError: invalid index to scalar variable.

In [41]:
b[1]

IndexError: invalid index to scalar variable.

In [42]:
a[::-1]

array([3, 2, 1])

In [43]:
b.mean()

21.0

In [54]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [44]:
a=['b',2,3,4]

In [45]:
a.insert(2,5)

In [46]:
a

['b', 2, 5, 3, 4]

In [47]:
a.pop()

4

In [48]:
a

['b', 2, 5, 3]

In [49]:
a[0:3:2]

['b', 5]

In [50]:
a=str(a)

In [51]:
a

"['b', 2, 5, 3]"

In [52]:
b=a.split(' ')

In [53]:
b[0]

"['b',"

In [54]:
b

["['b',", '2,', '5,', '3]']

In [70]:
''.join(b)

"['b',2,5,3,4]"

In [71]:
b

["['b',", '2,', '5,', '3,', '4]']

In [72]:
b.insert(3,10)

In [73]:
b

["['b',", '2,', '5,', 10, '3,', '4]']