In [ ]:
n='1 2 3 4'
arr = [int(arr_temp) for arr_temp in n.strip().split(' ')]
arr

In [ ]:
arr.reverse()
print(" ".join((map(str, arr))))

In [24]:
import numpy as np
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [3]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [27]:
 np.arange(10,25,2)

array([10, 12, 14, 16, 18, 20, 22, 24])

In [29]:
list(range(-1,10,2))

[-1, 1, 3, 5, 7, 9]

In [28]:
 np.linspace(0,2,9) 

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [30]:
np.eye(3,3,3)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [31]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [18]:
for i in range(1,11):
    print (i)

1
2
3
4
5
6
7
8
9
10


In [19]:
i = 1
while i<=10:
    print (i)
    i+=1

1
2
3
4
5
6
7
8
9
10


In [32]:
a= 10
b=20
if a < b:
    print("{} is less than {}".format(a,b))
elif a== b :
    print("{} is  equal to {}".format(a,b))
else:
    print("{} is  greater the to {}".format(a,b))
    

10 is less than 20


In [33]:
import os
os.chdir('fdklad')


FileNotFoundError: [WinError 2] The system cannot find the file specified: 'fdklad'

In [24]:
##Fizz Buss
for num in range (1,101):
    if num % 5 ==0 and num % 3 == 0:
        print("Fizzbuzz")
    elif num% 3 == 0:
        print ("Fizz")
    elif num% 5 == 0:
        print("Buzz")
    else:
        print(num)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
Fizzbuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
Fizzbuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
Fizzbuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
Fizzbuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
Fizzbuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
Fizzbuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [34]:
#fibonnoci sequence
a,b=0,1
for i in range(0,10):
    print(a)
    a,b=b,a+b

0
1
1
2
3
5
8
13
21
34


In [51]:
#basic data types and iteration over it
my_list = [10,20,30,40,50]
print(my_list[3])
for i in my_list:
    print (i)

40
10
20
30
40
50


In [49]:
my_tup =(1,5,2,9,5)
print(my_tup[1])
for i in my_tup:
    print(i)

5
1
5
2
9
5


In [36]:
my_dict = {'name':'a', 'age':'20','occ':'manager'}
print (my_dict['name'])
for key,value in my_dict.items:
    print(key,value)

a


TypeError: 'builtin_function_or_method' object is not iterable

In [37]:
my_set = {10,20,30,40,50,10,200}

for i in my_set:
    print (i)

40
200
10
50
20
30


In [38]:
##list comprehensions
a=[  i**2 for i in list(range(10,30,3))]
print(a)

[100, 169, 256, 361, 484, 625, 784]


In [40]:
##Generators_fibonnoci #error correct 
def fib(num):
    a,b=0,1
    for i in range(0,10):
        yeild ("{}: {}".format(i+1,a))
        a,b=b,a+b
for item in fib(10):
    print(item)

NameError: name 'yeild' is not defined

In [9]:
#dictionary
exdict = {'maz':28,'faz':27,'Izel':'1','uppa':61, 'umma':57}
exdict['maz']
'maz' in exdict
exdict.keys()



In [11]:
exdict1={'fenil':5,'zaya':3,'heza':1.5}

In [12]:
exdict.update(exdict1)

In [17]:
exdict.get('ma',0)

0

In [19]:
len(exdict)

8

In [20]:
exdict['heza']=1.3

In [21]:
exdict

{'Izel': '1',
 'faz': 27,
 'fenil': 5,
 'heza': 1.3,
 'maz': 28,
 'umma': 57,
 'uppa': 61,
 'zaya': 3}

In [22]:
del exdict['maz']

In [23]:
exdict

{'Izel': '1',
 'faz': 27,
 'fenil': 5,
 'heza': 1.3,
 'umma': 57,
 'uppa': 61,
 'zaya': 3}